const memberList = [
    // 好哇塞
    // {name: "朱誉榕"},
    // {name: "黄清梅"},
    // {name: "钟南欣"},
    // {name: "张宏杰"},
    // {name: "刘丽"},
    // {name: "廖继阳"},
    // // 帝恩思
    // {name: "刘娟娟"},
    // {name: "蒲丽萍"},
    // {name: "荣文鹭"},
    // {name: "宋生"},
    // {name: "苏国城"},
    // {name: "苏秋梅"},
    // {name: "王樊斌"},
    // {name: "吴强"},
    // {name: "肖晓丽"},
    // {name: "张丹丹"},
    // {name: "郑彬彬"},
    // {name: "周艺斌"},
    // {name: "陈家路"},
    // {name: "陈江中"},
    // {name: "陈斯毅"},
    // {name: "陈小莲"},
    // {name: "陈旭"},
    // {name: "陈雅韵"},
    // {name: "高丽娇"},
    // {name: "郭勤芬"},
    // {name: "何艺城"},
    // {name: "胡江华"},
    // {name: "胡善辉"},
    // {name: "黄华希"},
    // {name: "黄蕾"},
    // {name: "黄志鑫"},
    // {name: "杨志敏"},
    // {name: "李健"},
    // {name: "李向忠"},
    // {name: "李源铭"},
    // {name: "林达祥"},
    // {name: "林耿和"},
    // {name: "林锦坤"},
    // // 小快
    // {name: "沈永胜"},
    // {name: "田善锦"},
    // {name: "王楚云"},
    // {name: "王丽平"},
    // {name: "王文桂"},
    // {name: "王颖伟"},
    // {name: "王友铭"},
    // {name: "吴蔓"},
    // {name: "吴叶生"},
    // {name: "许泓森"},
    // {name: "颜明朗"},
    // {name: "杨淑云"},
    // {name: "杨帅"},
    // {name: "杨燕萍"},
    // {name: "杨志伟"},
    // {name: "游政贤"},
    // {name: "张佳萍"},
    // {name: "张贤智"},
    // {name: "郑俊杰"},
    // {name: "钟久鸣"},
    // {name: "钟志毅"},
    // {name: "Jason"},
    // {name: "包权"},
    // {name: "蔡依敏"},
    // {name: "陈伯威"},
    // {name: "陈嘉耀"},
    // {name: "陈建芳"},
    // {name: "陈丽明"},
    // {name: "陈露露"},
    // {name: "陈宁"},
    // {name: "陈微"},
    // {name: "方云麟"},
    // {name: "甘进益"},
    // {name: "侯继兴"},
    // {name: "侯宗魏"},
    // {name: "黄森"},
    // {name: "黄晓莹"},
    // {name: "黄新芳"},
    // {name: "孔燕凌"},
    // {name: "李思维"},
    // {name: "廖超颖"},
    // {name: "林坚超"},
    // {name: "林杰鸿"},
    // {name: "林金良"},
    // {name: "刘晓妍"},
    // {name: "刘作诚"},
    // {name: "龙芳"},
    // {name: "欧奕祺"},
    // {name: "潘锦彬"},
    // {name: "阮金阳"},
    // {name: "蔡锐"},
    // {name: "许清"},

    // 其他
    {name: "A"},
    {name: "B"}, 
    {name: "C"},
    {name: "D"},
    {name: "E"},
    {name: "F"},
    {name: "G"},
    {name: "H"},
    {name: "I"},
    {name: "J"},
    {name: "K"},
    {name: "L"},
    {name: "M"},
    {name: "N"},

]

console.log(`参与抽奖人数一共 ${memberList.length} 人`)